### ISSUE TITLE
how to run this app?

### ISSUE THREAD

**Issue by suriyaJaay** [craigshoemaker/angular-ui-router-demo#1]
it throws me following error

XMLHttpRequest cannot load file:///F:/personal_profile_testing/cv/angular-ui-router-demo-gh-pages/angular-ui-router-demo-gh-pages/partials/home.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.(anonymous function) @ angular.min.js:86m @ angular.min.js:82f @ angular.min.js:80(anonymous function) @ angular.min.js:112$eval @ angular.min.js:125$digest @ angular.min.js:122$apply @ angular.min.js:126(anonymous function) @ angular.min.js:17e @ angular.min.js:36d @ angular.min.js:17tc @ angular.min.js:18Jd @ angular.min.js:17(anonymous function) @ angular.min.js:249a @ angular.min.js:163c @ angular.min.js:32

**Comment by craigshoemaker** [comment]
you need to run it under the context of a web server. There are a number of personal web servers you can use from modules available via Node.js or sometimes through your web editor. You can see the working version of the code here:  http://craigshoemaker.github.io/angular-ui-router-demo/#/
